### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by danilolutti** [HuangRunHua/FilerApp#1]
Where is the code?

**Comment by HuangRunHua** [comment]
This is not open source, only app can be downloaded

**Comment by Muffo** [comment]
The extension is great, but I would remove the link "Go to Github" from the main website. It implicitly suggests the extension is open source, which is not the case.

**Comment by HuangRunHua** [comment]
thanks for advice, but I am not a web developer no idea how to remove it 😂
