### ISSUE TITLE
Add German Language support

### ISSUE THREAD

**Issue by GeylanKalafMohe** [HuangRunHua/FilerApp#2]
Hi i would appreciate if you could add the german language for "Filer". An automatic update function would also be good

**Comment by HuangRunHua** [comment]
Hi there, thanks for the advice and I will think it over.

**Comment by HuangRunHua** [comment]
Filer now supports German language and you can download Filer on the [Mac App Store](https://apps.apple.com/cn/app/filerapp/id1626627609?l=en&mt=12), future updates will only available on Mac App Store. And before you using it please check [Tutorial of Using Filer](https://github.com/HuangRunHua/FilerApp/blob/main/guide.md) first.

**Comment by SwiftiSwift** [comment]
Thank you! very cool
