### ISSUE TITLE
软件是按功能收费的吗？

### ISSUE THREAD

**Issue by jrotty** [HuangRunHua/FilerApp#4]
付款完发下另两个功能没解锁，三个功能只解锁了一个，是每个功能6元是吗，不如直接标价18避免像我一样的误会了哈哈😄

**Comment by HuangRunHua** [comment]
你好，感谢使用本软件。软件的确是按功能收费的😂我才意识到原来价格一样会有歧义。Sent from my iPhoneOn May 6, 2023, at 21:19, jrotty ***@***.***> wrote:﻿
付款完发下另两个功能没解锁，三个功能只解锁了一个，是每个功能6元是吗，不如直接标价18避免像我一样的误会了哈哈😄

**Comment by jrotty** [comment]
ok
